language: python
sudo: false
python:
- '2.7'
- '2.6'
install:
- pip install -r dev-requirements.txt
# will need this when we automatically push to pypi
# - pip install twine
script: nosetests tests.py --with-coverage --cover-package=jsonrpclib
